# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# Use Ubuntu 14.04 Trusty support for better C++11 support
sudo: required
dist: trusty

language: R
sudo: true
cache: packages
warnings_are_errors: true

matrix:
 include:
   - os: linux
     r: release
     r_packages: covr
     after_success: Rscript -e 'covr::codecov()'
   - os: linux
     r: devel
   - os: osx
     r: release
   - os: osx
     r: devel
     r_packages:
      - Rcpp
      - testthat
      - knitr
      - rmarkdown
 allow_failures:
        - os: osx
 fast_finish: true


notifications:
  email:
    on_success: change
    on_failure: change
